### ISSUE TITLE
copy and paste password

### ISSUE THREAD

**Issue by nachocheezvartussin** [Borumer/Borum#35]
you can copy and paste your password to confirm it instead of just retyping it

**Comment by nachocheezvartussin** [comment]
wow what a great bug report!

**Comment by varunsingh87** [comment]
I'll look into this. I don't consider this a bug report, more a feature request or a hybrid of the two.

**Comment by ghost** [comment]
@Borumer Don't do it. Don't mess with the user's browser. By Copy + Pasting into an E-Mail confirmation field, the user accepts responsibility over what they type. If they are dumb enough to copy + paste a faulty address (it has happened to me) then it's their own damn fault.

**Comment by ghost** [comment]
If you want to make sure that the E-Mail confirmation works out, have the user check their E-Mail while your site waits ("Please open your webmail program in a new window"). Show the E-Mail address in big fat letters ("The confirmation E-Mail was sent to.... made an error? CLick here to change).

Even better, if you can, let the user have some kind of limited access without confirming. That way, they can log in straight away and you improve your chances to keep in touch with the visitor even if the confirmation mail is blocked due to other reasons (e.g. spam filters).

This comment and the above one was pasted from https://stackoverflow.com/a/1725500/9860982
